### ISSUE TITLE
4.7.1 API Endpoint 403 Error

### ISSUE THREAD

**Issue by DonRichards** [fcrepo4-exts/fcrepo4-vagrant#74]
Click the icon on http://localhost:8080/fcrepo/ to the Redora REST API endpoint (using user account adminuser)

![a](https://cloud.githubusercontent.com/assets/2738244/22308350/941a8262-e314-11e6-85f5-6e0ea296f221.png)

Results on http://localhost:8080/fcrepo/rest/

![a](https://cloud.githubusercontent.com/assets/2738244/22308371/a689a9dc-e314-11e6-8d85-fa16cb6e2b4f.png)

**Comment by whikloj** [comment]
Hi @DonRichards. You may have hit an error in the vagrant up, perhaps you could try `vagrant destroy` and `vagrant up` again.

I just pulled master to HEAD and was able to bring up tomcat with fedora 4.7.1.

**Comment by whikloj** [comment]
Sorry @DonRichards, my mistake.

The `adminuser` is not really an **admin** user and when using WebAC authentication only the **admin** users have default access. All other users only have access to resources that they have been granted rights to.

So until a WebAC authorization is added giving `adminuser` rights you get the default policy which is **deny**.

So you'll want to user the `fedoraAdmin` user to access the server until you add a WebAC authorization.
```
user account testuser, with password password1
user account adminuser, with password password2
admin account fedoraAdmin with the password secret3
```

**Comment by DonRichards** [comment]
Wow, just saw this. Thanks @whikloj
